### ISSUE TITLE
best.h5 file

### ISSUE THREAD

**Issue by ShizaAli** [dattran2346/xray-thesis#2]
Can you please upload best.h5 file? I am trying to implement your code and I don't have the required GPU to train the dataset.

**Comment by dattran2346** [comment]
Hi @ShizaAli, you can find the model in [chexnet](https://github.com/dattran2346/chestX-ray-14/blob/master/models/chexnet.h5) and [unet](https://github.com/dattran2346/chestX-ray-14/blob/master/models/unet.h5)

**Comment by bkonk** [comment]
Can you explain what you mean and how to access the best.h5 file?

**Comment by dattran2346** [comment]
Hi @bkonk, you can access the model under `/models`
