### ISSUE TITLE
usage of masks in training

### ISSUE THREAD

**Issue by aakash-saboo** [dattran2346/xray-thesis#7]
Hey
I am not able to understand how masks generated by UNET are used during the training?
apart from cropping the Xray, is there anything else being done using masks?

**Comment by dattran2346** [comment]
Hi, Deep Learning method is a very powerful feature learning machine, so it can be very easily learn irrelevant features for the task at hand. So by training on the cropped X-ray, you explicitly force the model to learn more discriminative features on the lung region, which is where the thoracic disease occurs and visible in the chest X-ray.

Another idea is to use the mask generated by the model as pseudo-label and train segmentation and classification jointly with segmentation as auxiliary task, the combine loss can be L_combine = L_classification + 0.1*L_segmentation. This can squeeze out a little extra point. I haven't test it yet, but you can try.

Hope this answer your question.
